-- 拾光 M5：售卖问卷、运营后台、售后与转化分析
-- 已运行 v0.4 的项目仅执行本文件。

alter table public.orders add column if not exists service_stage text not null default 'waiting_brief'
  check (service_stage in ('waiting_brief','brief_submitted','planning','producing','reviewing','delivered','closed'));
alter table public.orders add column if not exists priority text not null default 'normal'
  check (priority in ('low','normal','high','urgent'));
alter table public.orders add column if not exists due_at timestamptz;
alter table public.orders add column if not exists assignee text;
alter table public.orders add column if not exists internal_notes text;
alter table public.orders add column if not exists discount_amount integer not null default 0 check (discount_amount >= 0);
alter table public.orders add column if not exists promotion_code text;

create table if not exists public.order_briefs (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  recipient_name text not null,
  relationship text not null,
  occasion text not null,
  delivery_date date,
  preferred_theme text not null default 'film' check (preferred_theme in ('cinema','starlight','film','unsure')),
  tone text not null default 'warm' check (tone in ('warm','romantic','restrained','playful','solemn')),
  story_facts jsonb not null default '[]'::jsonb,
  must_include text,
  avoid_content text,
  contact_method text,
  special_requests text,
  status text not null default 'draft' check (status in ('draft','submitted','reviewed')),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists order_briefs_owner_updated_idx on public.order_briefs(owner_id, updated_at desc);

create table if not exists public.refund_requests (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 8 and 2000),
  status text not null default 'pending' check (status in ('pending','approved','rejected','refunded','cancelled')),
  admin_response text,
  requested_at timestamptz not null default now(),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists refund_requests_owner_created_idx on public.refund_requests(owner_id, created_at desc);
create index if not exists refund_requests_status_created_idx on public.refund_requests(status, created_at desc);

create table if not exists public.conversion_events (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 8 and 100),
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null check (char_length(event_name) between 2 and 80),
  path text not null default '/',
  referrer text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists conversion_events_name_created_idx on public.conversion_events(event_name, created_at desc);
create index if not exists conversion_events_session_created_idx on public.conversion_events(session_id, created_at desc);

create or replace function public.set_sales_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists order_briefs_set_updated_at on public.order_briefs;
create trigger order_briefs_set_updated_at before update on public.order_briefs
for each row execute function public.set_sales_updated_at();

drop trigger if exists refund_requests_set_updated_at on public.refund_requests;
create trigger refund_requests_set_updated_at before update on public.refund_requests
for each row execute function public.set_sales_updated_at();

alter table public.order_briefs enable row level security;
alter table public.refund_requests enable row level security;
alter table public.conversion_events enable row level security;

drop policy if exists "owners can read own briefs" on public.order_briefs;
create policy "owners can read own briefs" on public.order_briefs for select to authenticated
using ((select auth.uid()) = owner_id);
drop policy if exists "owners can insert own briefs" on public.order_briefs;
create policy "owners can insert own briefs" on public.order_briefs for insert to authenticated
with check ((select auth.uid()) = owner_id and exists (
  select 1 from public.orders where orders.id = order_briefs.order_id and orders.owner_id = (select auth.uid())
));
drop policy if exists "owners can update own briefs" on public.order_briefs;
create policy "owners can update own briefs" on public.order_briefs for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "owners can read own refund requests" on public.refund_requests;
create policy "owners can read own refund requests" on public.refund_requests for select to authenticated
using ((select auth.uid()) = owner_id);
drop policy if exists "owners can create own refund requests" on public.refund_requests;
create policy "owners can create own refund requests" on public.refund_requests for insert to authenticated
with check ((select auth.uid()) = owner_id and exists (
  select 1 from public.orders where orders.id = refund_requests.order_id and orders.owner_id = (select auth.uid())
));

revoke all on public.order_briefs from anon;
revoke all on public.refund_requests from anon;
revoke all on public.conversion_events from anon, authenticated;
grant select, insert, update on public.order_briefs to authenticated;
grant select, insert on public.refund_requests to authenticated;
-- conversion_events 只能经服务端 API 使用 service_role 写入与读取。
